// YouTube subscribe request headers. Update from DevTools when session expires.
module.exports = {
  headers: {
    "accept": "*/*",
    "Cookie": "XXXXXxxxxxx",
    "accept-language": "en-GB,en-US;q=0.9,en;q=0.8",
    "authorization": "SAPISIDHASH XXXXXX_u SAPISID3PHASH XXXXXX_u",
    "content-type": "application/json",
    "device-memory": "8",
    "priority": "u=1, i",
    "sec-ch-dpr": "1",
    "sec-ch-ua": "\"Not:A-Brand\";v=\"99\", \"Google Chrome\";v=\"145\", \"Chromium\";v=\"145\"",
    "sec-ch-ua-arch": "\"arm\"",
    "sec-ch-ua-bitness": "\"64\"",
    "sec-ch-ua-form-factors": "\"Desktop\"",
    "sec-ch-ua-full-version": "\"145.0.7632.76\"",
    "sec-ch-ua-full-version-list": "\"Not:A-Brand\";v=\"99.0.0.0\", \"Google Chrome\";v=\"145.0.7632.76\", \"Chromium\";v=\"145.0.7632.76\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-model": "\"\"",
    "sec-ch-ua-platform": "\"macOS\"",
    "sec-ch-ua-platform-version": "\"26.3.0\"",
    "sec-ch-ua-wow64": "?0",
    "sec-ch-viewport-width": "3440",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "same-origin",
    "sec-fetch-site": "same-origin",
    "x-browser-channel": "stable",
    "x-browser-copyright": "Copyright 2026 Google LLC. All Rights reserved.",
    "x-browser-validation": "xxxxxxxx=",
    "x-browser-year": "2026",
    "x-client-data": "xxxxxxxxxx",
    "x-goog-authuser": "0",
    "x-goog-visitor-id": "xxxxxxxx",
    "x-origin": "https://www.youtube.com",
    "x-youtube-bootstrap-logged-in": "true",
    "x-youtube-client-name": "1",
    "x-youtube-client-version": "2.20260213.01.00"
  },
  referrer: "https://www.youtube.com/feed/channels"
};
